info:
  app:
    name: @project.artifactId@
    description: @project.description@
    version: @project.version@
    
server:
  port: 8091

spring:
  application:
    name: @project.artifactId@
  db:
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://127.0.0.1:5432/mytestdb
      username: mytest
      password: a12345!
      minimumIdle: 30
      maximumPoolSize: 30
      connectionTestQuery: select 1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
          
etm:
  accesskey:
    valid-interval: 300000
  redis:
    login-token:
      host: 127.0.0.1
      port: 6379
      database: 10