info:
  app:
    name: ^project.artifactId^
    description: ^project.description^
    version: ^project.version^
    
server:
  port: 8091

spring:
  application:
    name: ^project.artifactId^
  db:
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://pgsql:5432/mytestdb
      username: mytest
      password: a12345!
      minimumIdle: 30
      maximumPoolSize: 30
      connectionTestQuery: select 1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://etm-infra-eureka:8761/eureka
  instance:
    preferIpAddress: true
          
etm:
  accesskey:
    valid-interval: 300000
  redis:
    login-token:
      host: dingrr
      port: 6379
      database: 10
  encryption:
    key: dgnyzs4zq532uukbgvsuy5n8dyvvytfy,uy684hs4sns9zan67yju4res3ctkmmye,3z5rdj5gjaauncynh2mmkp7qg2mqw9wz,ahttt4ndzxnaa4g3898x5fxwhexx249b,hz6e7gbubdm7wr4twn3spyqhfxwp38kh,v33s8vrzsxjfbyt845snr8dthmah3ygu,8vs98kakbsyzpprcg9bq56qvsz37kr44,yygg65av2trm6bj4erasjzz2tn72a7z7,zqsfx8944x43ggfaknpwajgxbjxxbh8r,3bphdtvxzzn82fk6g877xhbbeex3zmqt,qtcs5uan5n36zxujzj2tzwgfzb8s8ztt,5nbc8sdvtc8wdpjqy8p9u5cqsva7fqv3,dwnuvue4esg6pdjanrskm65hxw7a75kp,7j23hwvuc9ksgdmt9j25zkmgdgksu5es,jdht4qzkdwg2gc5n3huz9xfdueysvdwa,t7bg9dexeqyvt5wqny8uuqem6sz3c3ju,d73gt86uew25uc6ep3qzvpzvvxpubqx4,n4p3dcggva4jwum339v2c2adt7hz8dwr,5r6gzmkhjs9p6g5y7qtxun9d8j2s54b8,vxbfspbem9pbkp9ynk9m82jhe3dahu4e,qzemd5h4bah4rbm8xnqzc73m2m3w4hqz,m3kbyhkfc6ukmkb8vd8tre7xv2xru6yz,vucna95ttf4562t2hkvnndrgm85qndbc,awdscbxq3zwx96yjfqf8v2juus7mame6,2q7x3tn2c5zfxe55jdvn34mxhs26gpxr,zxejcct7dttdrq9f3pb83xqffnp4ns7w,hj7z7hueqvnkzf242ucs29v3dtged3zx,8xuf977nxbm2qdprga4kkat7gmmtyamk,vw42k24bx2nk69v4hhnah6bz74mhfzhj,rcjc3jjjptqq8pcp7w8nyw6pfspjt674,jpg3d89f7tjfqdb72cwp2wr8d7tsapuh,fh6su8ddp7zqcbucndvncsegb6j5m2fh,dh27r9ykba32e9es6vk4e73yeqfj9de7,crsm3yubhhw85msn3shgwjeq2edc994y,vcjnx9yn75ptfcszd8hg6mge2bygfvqm,uneczjpdhw32tpvcv73nyjp8e6xqebau,9j6c3hhvfe48ch9ru5enbgd9dg5hfxhu,25asvst3v8kkegsj8pd6vemns2rt5vaq,zvuq7jsz3vkda5ay58uxz8epnvurgrct,7n82byj9hw52uqm48xx6gf25vmc4433t,smrm7an3wjymvm2j362cb3p9m8eb2u4w,fw4m7rccq62jvxxw2fb4swuxa7e5ttst,rmpxn8a5crzp2wvaa9wcxc4b4pujw743,a9z9h9p7u6ujnbzabz8bg6hh63bg58pf,3ks9pehffr3yeggcsmcstfm998v9mz8b,bspwzw38tyku88yxbgrp2ssgbvm6dkzv,5gnnxu4xtman7gkh476nbjkvapgzw6gs,q2ug754j22et6prefzz7jgteqeq87227,nkc7s2awxq2r6kkrbbfub573cjjkn5sp,dqzug832szva8hhkyhnbw57abpdn99t7