info:
  app:
    name: ^project.artifactId^
    description: ^project.description^
    version: ^project.version^
    
server:
  port: 8092

spring:
  application:
    name: ^project.artifactId^
  db:
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://pgsql:5432/mytestdb
      username: mytest
      password: a12345!
      minimumIdle: 30
      maximumPoolSize: 30
      connectionTestQuery: select 1

kafka:
  bootstrapAddress: kafka-svc:9092
  consumer:
    group-id: event-engine
    topic: base-event
    auto_offset_reset: latest
    enable-auto-commit: true
    auto-commit-interval: 1000
    max-poll-records: 10
  producer:
    topic: alarm-event
  
zk:
  conn: zk-svc:2181
  sessionTimeoutMs: 3000
  offsets: /etm/offsets/event-engine
  
websocket:
  enable: true
  host: etm-svc-websocket
  port: 8093
  end-points: /ws
  brokers:  /topic
  destination-prefixes: /app
  api-key: 52f16570-a657-11eb-bcbc-0242ac130002  