info:
  app:
    name: ^project.artifactId^
    description: ^project.description^
    version: ^project.version^
    
server:
  port: 8090

spring:
  application:
    name: ^project.artifactId^

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://etm-infra-eureka:8761/eureka
  instance:
    preferIpAddress: true

websocket:
  enable: true
  host: etm-svc-websocket
  port: 8093
  end-points: /ws
  brokers:  /topic
  destination-prefixes: /app
  api-key: 52f16570-a657-11eb-bcbc-0242ac130002
      