kind: ConfigMap
apiVersion: v1
metadata:
  name: etm-infra-eureka
data:
  application.yml: |-
    eureka:
      client:
        register-with-eureka: false
        fetch-registry: false
        serviceUrl: 
          defaultZone: http://etm-infra-eureka-lb:8761/eureka
      instance:
        prefer-ip-address: false
        leaseRenewalIntervalInSeconds: 30
        leaseExpirationDurationInSeconds: 30
        hostname: ${MY_POD_NAME}
      server:
        wait-time-in-ms-when-sync-empty: 0
        eviction-interval-timer-in-ms: 15000
