# 사용 안함
apiVersion: v1
kind: Service
metadata:
  name: etm-svc-control-lb
  labels:
    component: etm-svc-control
spec:
  selector:
    component: etm-svc-control
  ports:
  - protocol: "TCP"
    port: 8090
    targetPort: 8090
  type: LoadBalancer
  externalIPs:
    - 10.250.238.36
